### PR TITLE
AUTOCOMPLETION BABEY

### PR DESCRIPTION
**Pull request by SirNapkin1334**
dude the minecraft source code that uses this is absolute garbage, jesus christ mojang has an obsession with nested ternaries

### CODE REVIEW

**Comment by SirNapkin1334** [comment]
okay you can merge now

**Comment by isXander** [comment]
this good u should merge this asap or u r weird

**Comment by FalseHonesty** [comment]
@SirNapkin1334 Can you please squash your commits into a single unified commit :)

**Comment by SirNapkin1334** [comment]
It seems the commit description had a bunch of random stuff tacked on, I don't know why. I thought that the last part of it would become the new commit message, but I guess not...

**Comment by FalseHonesty** [comment]
Ah, looks much better! If you wish to change the commit message you can do so with the `git commit --amend` command, and then force push to your branch. I hope you recognize I wasn't trying to be pedantic with this request, rather, I was trying to ease you into becoming more familiar with git, a skill many people wish they have!

**Comment by SirNapkin1334** [comment]
Yeah that's what I thought. Thank you.

**Comment by asbyth** [comment]
remembered this existed because of someone forking autogg then subsequently deleting it, merging

**Pull request merged**
